import { describe, it, expect } from "vitest";
import {
  feeShareForDuration,
  penaltyBpsForRemaining,
  LOCK_MIN_DURATION_SECS,
  LOCK_HALF_LIFE_SECS,
  LOCK_MAX_BOOST_BPS,
  LOCK_MAX_PENALTY_BPS,
} from "@parlaycity/shared";

// Fixtures generated by the Solidity formula directly.
// Any drift from LockVaultV2.sol must break this test.
const SECS_PER_DAY = 86_400n;

describe("feeShareForDuration", () => {
  it("returns 10_000 (1.0x) at the minimum duration boundary", () => {
    // At d = MIN_LOCK_DURATION (7 days), boost = 30000*7 / (7 + 730) ≈ 284
    const result = feeShareForDuration(LOCK_MIN_DURATION_SECS);
    const expected = 10_000n + (LOCK_MAX_BOOST_BPS * LOCK_MIN_DURATION_SECS) /
      (LOCK_MIN_DURATION_SECS + LOCK_HALF_LIFE_SECS);
    expect(result).toBe(expected);
  });

  it("hits exactly 2.0x at 365 days (marketing hook)", () => {
    const oneYear = 365n * SECS_PER_DAY;
    // 30_000 * 365 / (365 + 730) = 30_000 * 365 / 1095 = 10_000 exactly
    expect(feeShareForDuration(oneYear)).toBe(20_000n);
  });

  it("hits 2.5x at 2 years (730d = HALF_LIFE)", () => {
    // 30_000 * 730 / (730 + 730) = 15_000
    expect(feeShareForDuration(730n * SECS_PER_DAY)).toBe(25_000n);
  });

  it("is monotonically increasing across sampled durations", () => {
    const samples = [7n, 30n, 60n, 90n, 180n, 365n, 730n, 1825n, 3650n, 36_500n];
    let prev = 0n;
    for (const d of samples) {
      const fs = feeShareForDuration(d * SECS_PER_DAY);
      expect(fs).toBeGreaterThan(prev);
      prev = fs;
    }
  });

  it("stays strictly below asymptote (40_000) even at 100 years", () => {
    const hundredYears = 36_500n * SECS_PER_DAY;
    const fs = feeShareForDuration(hundredYears);
    expect(fs).toBeLessThan(40_000n);
    expect(fs).toBeGreaterThan(39_000n);
  });

  it("reverts below minimum duration", () => {
    expect(() => feeShareForDuration(LOCK_MIN_DURATION_SECS - 1n)).toThrow();
    expect(() => feeShareForDuration(0n)).toThrow();
  });

  it("matches expected values at the plan's advertised schedule", () => {
    // Values from docs/A-DAY.md plan table.
    const cases: [bigint, bigint][] = [
      [7n * SECS_PER_DAY, 10_284n],       // ~1.028x
      [30n * SECS_PER_DAY, 11_184n],      // ~1.118x
      [90n * SECS_PER_DAY, 13_292n],      // ~1.329x
      [180n * SECS_PER_DAY, 15_934n],     // ~1.593x
      [365n * SECS_PER_DAY, 20_000n],     // 2.0x
      [730n * SECS_PER_DAY, 25_000n],     // 2.5x
      [1825n * SECS_PER_DAY, 31_428n],    // ~3.14x
      [3650n * SECS_PER_DAY, 35_000n],    // 3.50x
    ];
    for (const [dur, expected] of cases) {
      expect(feeShareForDuration(dur)).toBe(expected);
    }
  });
});

describe("penaltyBpsForRemaining", () => {
  it("returns 0 at remaining = 0 (lock matured)", () => {
    expect(penaltyBpsForRemaining(0n)).toBe(0n);
  });

  it("matches asymptotic formula for sampled remaining times", () => {
    const cases: [bigint, bigint][] = [
      [30n * SECS_PER_DAY, 118n],          // 30d remaining: ~1.18%
      [90n * SECS_PER_DAY, 329n],          // 90d remaining: ~3.29%
      [365n * SECS_PER_DAY, 1000n],        // 1yr remaining: 10.00%
      [730n * SECS_PER_DAY, 1500n],        // 2yr remaining: 15.00%
      [1825n * SECS_PER_DAY, 2142n],       // 5yr remaining: ~21.42%
    ];
    for (const [rem, expected] of cases) {
      expect(penaltyBpsForRemaining(rem)).toBe(expected);
    }
  });

  it("stays strictly below MAX_PENALTY_BPS (3000) at extreme remaining", () => {
    const p = penaltyBpsForRemaining(36_500n * SECS_PER_DAY);
    expect(p).toBeLessThan(LOCK_MAX_PENALTY_BPS);
    expect(p).toBeGreaterThan(LOCK_MAX_PENALTY_BPS - 100n);
  });

  it("is monotonically non-decreasing with remaining time", () => {
    let prev = 0n;
    for (let days = 0n; days <= 3650n; days += 30n) {
      const p = penaltyBpsForRemaining(days * SECS_PER_DAY);
      expect(p).toBeGreaterThanOrEqual(prev);
      prev = p;
    }
  });
});
