/**
 * Helper types derived from the autogenerated `deployedContracts.ts`. The
 * source repo's generator wrote these directly into the same file; SE-2's
 * generator emits a plainer shape, so we pull them out here. Keeping them in
 * a separate file means the autogenerated file stays untouched between
 * deploys.
 */
import deployedContracts from "./deployedContracts";

export type DeployedContracts = typeof deployedContracts;
export type SupportedDeployedChainId = keyof DeployedContracts;
// Mapped-type so the default `C` does not collapse to an intersection;
// passing a specific `C` narrows to that chain's contract names.
export type ContractName<C extends SupportedDeployedChainId = SupportedDeployedChainId> = {
  [K in C]: keyof DeployedContracts[K];
}[C];
