/**
 * Deployed contract addresses + ABIs, keyed by chainId.
 *
 * REGENERATED by `scripts/generate-deployed-contracts.ts`, which is chained
 * onto `pnpm deploy:local` and `pnpm deploy:sepolia`. Do not edit by hand —
 * the next deploy will overwrite it.
 *
 * This bootstrap version was hand-seeded with the Base Sepolia v2 deployment
 * (see root CLAUDE.md). ABIs are inlined here so this file has no imports
 * from `src/lib/*` (which avoids an import cycle with the legacy
 * `lib/contracts.ts` re-export shim). After `pnpm deploy:*`, the generator
 * overwrites this file using ABIs from `packages/foundry/out/`.
 */
import {LOCAL_CHAIN_ID, BASE_SEPOLIA_CHAIN_ID} from "@parlaycity/shared";

const USDC_ABI = [
  {
    name: "approve",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {name: "spender", type: "address"},
      {name: "amount", type: "uint256"},
    ],
    outputs: [{name: "", type: "bool"}],
  },
  {
    name: "balanceOf",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "account", type: "address"}],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "allowance",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "owner", type: "address"},
      {name: "spender", type: "address"},
    ],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "transfer",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {name: "to", type: "address"},
      {name: "amount", type: "uint256"},
    ],
    outputs: [{name: "", type: "bool"}],
  },
  {
    name: "decimals",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint8"}],
  },
  {
    name: "mint",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {name: "to", type: "address"},
      {name: "amount", type: "uint256"},
    ],
    outputs: [],
  },
] as const;

const HOUSE_VAULT_ABI = [
  {
    name: "deposit",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {name: "assets", type: "uint256"},
      {name: "receiver", type: "address"},
    ],
    outputs: [{name: "shares", type: "uint256"}],
  },
  {
    name: "withdraw",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {name: "shares", type: "uint256"},
      {name: "receiver", type: "address"},
    ],
    outputs: [{name: "assets", type: "uint256"}],
  },
  {
    name: "totalAssets",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "totalReserved",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "maxUtilizationBps",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "freeLiquidity",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "balanceOf",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "account", type: "address"}],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "convertToAssets",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "shares", type: "uint256"}],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "maxPayout",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
] as const;

const PARLAY_ENGINE_ABI = [
  {
    name: "buyTicketSigned",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "quote",
        type: "tuple",
        components: [
          {name: "buyer", type: "address"},
          {name: "stake", type: "uint256"},
          {
            name: "legs",
            type: "tuple[]",
            components: [
              {name: "sourceRef", type: "string"},
              {name: "outcome", type: "bytes32"},
              {name: "probabilityPPM", type: "uint256"},
              {name: "cutoffTime", type: "uint256"},
              {name: "earliestResolve", type: "uint256"},
              {name: "oracleAdapter", type: "address"},
            ],
          },
          {name: "deadline", type: "uint256"},
          {name: "nonce", type: "uint256"},
        ],
      },
      {name: "signature", type: "bytes"},
    ],
    outputs: [{name: "ticketId", type: "uint256"}],
  },
  {
    name: "settleTicket",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "ticketId", type: "uint256"}],
    outputs: [],
  },
  {
    name: "claimPayout",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "ticketId", type: "uint256"}],
    outputs: [],
  },
  {
    name: "getTicket",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "ticketId", type: "uint256"}],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          {name: "buyer", type: "address"},
          {name: "stake", type: "uint256"},
          {name: "legIds", type: "uint256[]"},
          {name: "outcomes", type: "bytes32[]"},
          {name: "multiplierX1e6", type: "uint256"},
          {name: "potentialPayout", type: "uint256"},
          {name: "feePaid", type: "uint256"},
          {name: "mode", type: "uint8"},
          {name: "status", type: "uint8"},
          {name: "createdAt", type: "uint256"},
        ],
      },
    ],
  },
  {
    name: "ticketCount",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "baseFee",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "perLegFee",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "minStake",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "maxLegs",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "ownerOf",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "tokenId", type: "uint256"}],
    outputs: [{name: "", type: "address"}],
  },
  {
    name: "cashoutEarly",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {name: "ticketId", type: "uint256"},
      {name: "minOut", type: "uint256"},
    ],
    outputs: [],
  },
  {
    name: "TicketPurchased",
    type: "event",
    inputs: [
      {name: "ticketId", type: "uint256", indexed: true},
      {name: "buyer", type: "address", indexed: true},
      {name: "legIds", type: "uint256[]", indexed: false},
      {name: "outcomes", type: "bytes32[]", indexed: false},
      {name: "stake", type: "uint256", indexed: false},
      {name: "multiplierX1e6", type: "uint256", indexed: false},
      {name: "potentialPayout", type: "uint256", indexed: false},
      {name: "mode", type: "uint8", indexed: false},
    ],
  },
] as const;

const LEG_REGISTRY_ABI = [
  {
    name: "getLeg",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "legId", type: "uint256"}],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          {name: "question", type: "string"},
          {name: "sourceRef", type: "string"},
          {name: "cutoffTime", type: "uint256"},
          {name: "earliestResolve", type: "uint256"},
          {name: "oracleAdapter", type: "address"},
          {name: "probabilityPPM", type: "uint256"},
          {name: "active", type: "bool"},
        ],
      },
    ],
  },
  {
    name: "legCount",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "createLeg",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {name: "question", type: "string"},
      {name: "sourceRef", type: "string"},
      {name: "cutoffTime", type: "uint256"},
      {name: "earliestResolve", type: "uint256"},
      {name: "oracleAdapter", type: "address"},
      {name: "probabilityPPM", type: "uint256"},
    ],
    outputs: [{name: "legId", type: "uint256"}],
  },
] as const;

const LOCK_VAULT_ABI = [
  {
    name: "lock",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {name: "shares", type: "uint256"},
      {name: "tier", type: "uint8"},
    ],
    outputs: [{name: "positionId", type: "uint256"}],
  },
  {
    name: "unlock",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "positionId", type: "uint256"}],
    outputs: [],
  },
  {
    name: "earlyWithdraw",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "positionId", type: "uint256"}],
    outputs: [],
  },
  {
    name: "claimFees",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "positions",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "positionId", type: "uint256"}],
    outputs: [
      {name: "owner", type: "address"},
      {name: "shares", type: "uint256"},
      {name: "tier", type: "uint8"},
      {name: "lockedAt", type: "uint256"},
      {name: "unlockAt", type: "uint256"},
      {name: "feeMultiplierBps", type: "uint256"},
      {name: "rewardDebt", type: "uint256"},
    ],
  },
  {
    name: "nextPositionId",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "totalLockedShares",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "pendingRewards",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "user", type: "address"}],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "pendingReward",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "positionId", type: "uint256"}],
    outputs: [{name: "", type: "uint256"}],
  },
] as const;

const ADMIN_ORACLE_ABI = [
  {
    name: "resolve",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {name: "legId", type: "uint256"},
      {name: "status", type: "uint8"},
      {name: "outcome", type: "bytes32"},
    ],
    outputs: [],
  },
] as const;

const deployedContracts = {
  [LOCAL_CHAIN_ID]: {
    // Anvil deploys are deterministic but only exist after `pnpm deploy:local`.
    // The generator populates this entry from forge broadcast/run-latest.json.
  },
  [BASE_SEPOLIA_CHAIN_ID]: {
    MockUSDC: {
      address: "0xBf68FAa69faA3b42FFDEA2C033dF795706F6362b" as `0x${string}`,
      abi: USDC_ABI,
    },
    HouseVault: {
      address: "0xeF9334cA8C7cb7F081e4A53005020CD2F939A979" as `0x${string}`,
      abi: HOUSE_VAULT_ABI,
    },
    ParlayEngine: {
      address: "0x8463CF3D7EE71Be38dDD10f83BA64689033eFDd2" as `0x${string}`,
      abi: PARLAY_ENGINE_ABI,
    },
    LegRegistry: {
      address: "0x2244D0f74469BD0ef8C47e7E5f7631E529D4c3bc" as `0x${string}`,
      abi: LEG_REGISTRY_ABI,
    },
    LockVault: {
      address: "0x75457799813D894078FEbec6Fed6602938635435" as `0x${string}`,
      abi: LOCK_VAULT_ABI,
    },
    AdminOracleAdapter: {
      address: "0x0000000000000000000000000000000000000000" as `0x${string}`,
      abi: ADMIN_ORACLE_ABI,
    },
  },
} as const;

export default deployedContracts;
export type DeployedContracts = typeof deployedContracts;
export type SupportedDeployedChainId = keyof DeployedContracts;
export type ContractName<C extends SupportedDeployedChainId> =
  keyof DeployedContracts[C];
