/**
 * Backwards-compatibility shim.
 *
 * The source of truth for addresses + ABIs is now
 * `src/contracts/deployedContracts.ts` (regenerated by
 * `scripts/generate-deployed-contracts.ts` after every deploy). New call sites
 * should prefer the `useDeployedContract` hook so they pick up the user's
 * active wagmi chain. This file keeps the legacy `contractAddresses` const +
 * named ABI exports working until `lib/hooks.ts` is migrated.
 *
 * `contractAddresses` resolves to whichever chain the frontend is pinned to
 * via `NEXT_PUBLIC_CHAIN_ID` (used elsewhere by `useContractClient`), falling
 * back to Base Sepolia if unset or unknown.
 */
import type {Abi} from "viem";
import deployedContracts, {
  type SupportedDeployedChainId,
} from "../contracts/deployedContracts";

const availableChainIds = Object.keys(deployedContracts).map(Number) as SupportedDeployedChainId[];

function pinnedChainId(): SupportedDeployedChainId {
  const raw = Number(process.env.NEXT_PUBLIC_CHAIN_ID);
  if (raw && raw in deployedContracts) {
    return raw as SupportedDeployedChainId;
  }
  return availableChainIds[0];
}

const chainEntry = deployedContracts[pinnedChainId()] as Record<
  string,
  {address: `0x${string}`; abi: Abi}
>;

function abiOf(name: string): Abi {
  // Empty fallback keeps type-checks happy on chains where the contract isn't
  // deployed; reads/writes will surface the empty-ABI error at call time.
  return chainEntry[name]?.abi ?? ([] as unknown as Abi);
}

function addressOf(name: string): `0x${string}` {
  return (
    chainEntry[name]?.address ??
    ("0x0000000000000000000000000000000000000000" as `0x${string}`)
  );
}

export const USDC_ABI = abiOf("MockUSDC");
export const HOUSE_VAULT_ABI = abiOf("HouseVault");
export const PARLAY_ENGINE_ABI = abiOf("ParlayEngine");
export const LEG_REGISTRY_ABI = abiOf("LegRegistry");
export const LOCK_VAULT_ABI = abiOf("LockVault");
export const ADMIN_ORACLE_ABI = abiOf("AdminOracleAdapter");

/** Generic IOracleAdapter view interface — not produced per-chain. */
export const ORACLE_ADAPTER_ABI = [
  {
    name: "getStatus",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "legId", type: "uint256"}],
    outputs: [
      {name: "status", type: "uint8"},
      {name: "outcome", type: "bytes32"},
    ],
  },
  {
    name: "canResolve",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "legId", type: "uint256"}],
    outputs: [{name: "", type: "bool"}],
  },
] as const;

/** LegStatus enum from IOracleAdapter.sol */
export const LEG_STATUS = {
  Unresolved: 0,
  Won: 1,
  Lost: 2,
  Voided: 3,
} as const;

export const contractAddresses = {
  usdc: addressOf("MockUSDC"),
  houseVault: addressOf("HouseVault"),
  parlayEngine: addressOf("ParlayEngine"),
  legRegistry: addressOf("LegRegistry"),
  lockVault: addressOf("LockVault"),
};
